linux: Fix compiling proc with gcc 11 and glibc 2.33.
Switch to using readdir to fix the use of a deprecated function.

proc.c: In function ‘process_tasks’:
proc.c:247:17: error: ‘readdir_r’ is deprecated [-Werror=deprecated-declarations]
  247 |                 if (readdir_r(d, &entry, &result) != 0) {
      |                 ^~
In file included from proc.c:31:
/usr/include/dirent.h:183:12: note: declared here
  183 | extern int readdir_r (DIR *__restrict __dirp,
      |            ^~~~~~~~~
cc1: all warnings being treated as errors

This is downstream Fedora patch: ltrace-0.7.91-tautology.patch
without the removal of the forced asserts. The downstream patches
to fix this can be removed.

Signed-off-by: Carlos O'Donell <carlos@redhat.com>